#!/bin/bash

RC_OK=0
RC_ERROR=1
RC_LOCK=2
RC_CONFIG_MISSED=3
RC_PANDOC_FILES=4
RC_ARGS=5

end_with_code() {
  local rc=$1
  if test -z "$rc";
  then
    rc=$RC_ERROR
  fi

  if test "$rc" -eq 0;
  then
    cleanup_working_folder
  fi

  verbose "[$FUNCNAME] exiting with RC=[$rc]"
  exit $rc
}

die() {
  verbose "[$FUNCNAME] 1:[$1] 2:[$2]"
  local message
  local rc

  if test $# -eq 2;
  then
    message=$1
    rc=$2
  else
    message=$1
    rc=$RC_ERROR
  fi

  echo -e "$$ $message" >&2
  end_with_code $rc
}

verbose() {
  if test "$VERBOSE" -ne 0;
  then
    echo "$$ $@"
  fi
}

debug() {
  if test "$DEBUG" -ne 0;
  then
    echo "$@"
  fi
}

init_check() {
  if test -e $LOCK_FILE;
  then
    die "[$FUNCNAME] lock=$LOCK_FILE exists. Wait compilation or erase it" $RC_LOCK
  fi

  # PANDOC_FILTER_BASE should exists
  if test ! -d "$PANDOC_FILTER_BASE";
  then
    die "[$FUNCNAME]: PANDOC_FILTER_BASE=$PANDOC_FILTER_BASE unavailable" $RC_PANDOC_FILES
  fi

  # PANDOC_INCLUDE_BASE should exists
  if test ! -d "$PANDOC_INCLUDE_BASE";
  then
    die "[$FUNCNAME]: PANDOC_INCLUDE_BASE=$PANDOC_INCLUDE_BASE unavailable" $RC_PANDOC_FILES
  fi

  # STORE should exists
  if test ! -d "$STORE" -o ! -w "$STORE";
  then
    die "[$FUNCNAME]: STORE=$STORE should be a writable folder"
  fi

  # WORKING_FOLDER should exists
  if test ! -d "$WORKING_FOLDER" -o ! -w "$WORKING_FOLDER";
  then
    die "[$FUNCNAME]: WORKING_FOLDER=$WORKING_FOLDER should be a writable folder"
  fi

  # external tools
  for tool in touch curl pandoc pdflatex
  do
    local tool_location=$(command -v $tool)
    if test "$tool_location";
    then
      verbose "[$FUNCNAME] $tool=$tool_location"
    else
      die "[$FUNCNAME] $tool unavailable"
    fi
  done
}

mirror_pad() {
  debug "[$FUNCNAME] ARGS:$@"
  if test $# -ne 2;
  then
    die 'usage: [$FUNCNAME] url filename'
  fi

  local url=$1
  local filename=$2
  verbose "[$FUNCNAME] url=$url filename=$filename"

  if test "$TRAVIS" = "true";
  then
    # test only public pads (with curl) if building in travis
    RESPONSE=$(curl --silent --show-error $url --output $filename 2>&1)
    RC=$?
  else
    RESPONSE=$(perl $base/mirror_pad.pl $url > "$filename")
    RC=$?
  fi

  local errstr="[$FUNCNAME] RC=[$RC] $RESPONSE"
  if test "$RC" -eq 0;
  then
    verbose "$errstr"
  else
    die "$errstr"
  fi
}

pad2json() {
  debug "[$FUNCNAME] ARGS:$@"
  if test $# -ne 2;
  then
    die "usage: [$FUNCNAME] input_file output_file"
  fi

  local input=$1
  local output=$2
  verbose "[$FUNCNAME] input=$input output=$output"
  RESPONSE=$(pandoc \
    -f markdown "$input" \
    -o "$output" -t json --self-contained)
  RC=$?
  local errstr="[$FUNCNAME] RC=[$RC] $RESPONSE"
  if test "$RC" -eq 0;
  then
    verbose "$errstr"
  else
    die "$errstr"
  fi
}

pad2docx() {
  debug "[$FUNCNAME] PWD:$PWD ARGS:$@"
  if test $# -ne 2;
  then
    die 'usage: [$FUNCNAME] input_file output_file'
  fi

  local input=$1
  local output=$2
  local refdoc="$PANDOC_INCLUDE_BASE/exegetes.docx"
  verbose "[$FUNCNAME] input=$input output=$output"

  if ! test -e "$refdoc";
  then
    die "[$FUNCNAME] refdoc=$refdoc unavailable"
  fi

  RESPONSE=$(pandoc \
    -f markdown "$input" \
    -o "$output" -t docx --self-contained --smart \
    --reference-docx="$refdoc" \
    --filter pandoc-citeproc \
    --filter $PANDOC_FILTER_BASE/docx.zsh \
    --filter $PANDOC_FILTER_BASE/nettoyage.zsh \
    --filter $PANDOC_FILTER_BASE/nettoyage-etendu.zsh)
  RC=$?
  local errstr="[$FUNCNAME] RC=[$RC] $RESPONSE"
  if test "$RC" -eq 0;
  then
    verbose "$errstr"
  else
    die "$errstr"
  fi
}

pad2html() {
  debug "[$FUNCNAME] ARGS:$@"
  if test $# -ne 2;
  then
    die 'usage: [$FUNCNAME] input_file output_file'
  fi

  local input=$1
  local output=$2
  verbose "[$FUNCNAME] input=$input output=$output"

  RESPONSE=$(pandoc \
    -f markdown "$input" \
    -o "$output" -t html --self-contained --smart \
    --filter pandoc-citeproc \
    --filter $PANDOC_FILTER_BASE/html.zsh \
    --filter $PANDOC_FILTER_BASE/nettoyage.zsh \
    --filter $PANDOC_FILTER_BASE/nettoyage-etendu.zsh)
  RC=$?
  local errstr="[$FUNCNAME] RC=[$RC] $RESPONSE"
  if test "$RC" -eq 0;
  then
    verbose "$errstr"
  else
    die "$errstr"
  fi
}

pad2markdown() {
  debug "[$FUNCNAME] ARGS:$@"
  if test $# -ne 2;
  then
    die 'usage: [$FUNCNAME] input_file output_file'
  fi

  local input=$1
  local output=$2
  verbose "[$FUNCNAME] input=$input output=$output"

  RESPONSE=$(pandoc \
    -f markdown "$input" \
    -o "$output" -t markdown --wrap=none --self-contained --smart \
    --reference-location=block --reference-links \
    --filter pandoc-citeproc \
    --filter $PANDOC_FILTER_BASE/markdown.zsh \
    --filter $PANDOC_FILTER_BASE/nettoyage.zsh \
    --filter $PANDOC_FILTER_BASE/nettoyage-etendu.zsh)
  RC=$?
  local errstr="[$FUNCNAME] RC=[$RC] $RESPONSE"
  if test "$RC" -eq 0;
  then
    verbose "$errstr"
  else
    die "$errstr"
  fi
}

pad2tex() {
  debug "[$FUNCNAME] ARGS:$@"
  if test $# -ne 2;
  then
    die 'usage: [$FUNCNAME] input_file output_file'
  fi

  local input=$1
  local output=$2
  verbose "[$FUNCNAME] input=$input output=$output"

  RESPONSE=$(pandoc \
    -f markdown "$input" \
    -o "$output" -t latex --self-contained \
    --template ../../exegetesDoc/pandocincludes/exegetes.latex \
    --filter pandoc-citeproc \
    --filter $PANDOC_FILTER_BASE/latex.zsh \
    --filter $PANDOC_FILTER_BASE/nettoyage.zsh \
    --filter pandoc-latex-environment \
    --filter $PANDOC_FILTER_BASE/paranumero.bash)
  RC=$?
  local errstr="[$FUNCNAME] RC=[$RC] $RESPONSE"
  if test "$RC" -eq 0;
  then
    verbose "$errstr"
  else
    die "$errstr"
  fi
}

tex2pdf() {
  debug "[$FUNCNAME] ARGS:$@"
  if test $# -ne 2;
  then
    die 'usage: [$FUNCNAME] input_file output_file'
  fi

  local input=$1
  local output=$2
  verbose "[$FUNCNAME] input=$input output=$output"

  # pdflatex sort avec un code 1 mais genere le PDF on peut pas die sur RC>0 ici
  pdflatex -interaction=nonstopmode -output-directory="$WORKING_FOLDER" "$input" > "$WORKING_FOLDER/pdflatex_passe1.log" 2>&1
  verbose "[$FUNCNAME] Passe 1 RC=[$?]"
  pdflatex -interaction=nonstopmode -output-directory="$WORKING_FOLDER" "$input" > "$WORKING_FOLDER/pdflatex_passe2.log" 2>&1
  verbose "[$FUNCNAME] Passe 2 RC=[$?]"
  if test ! -e "$output";
  then
    die "[$FUNCNAME] Génération du PDF '$putput' en erreur"
  fi
}

lock_project() {
  verbose "[$FUNCNAME] LOCKFILE=$LOCK_FILE PID=$$ locked"
  if test ! -e "$LOCK_FILE";
  then
    echo "$$" > "$LOCK_FILE"
  else
    die "lockfile $LOCK_FILE already exists" $RC_LOCK
  fi
}

unlock_project() {
  if test -e "$LOCK_FILE";
  then
    local locker_pid=$(cat "$LOCK_FILE")
    verbose "[$FUNCNAME] lockfile=$LOCK_FILE lockerpid=$locker_pid pid=$$"

    if test "$locker_pid" -eq "$$";
    then
      rm -f "$LOCK_FILE"

      if test ! -e "$LOCK_FILE";
      then
        verbose "[$FUNCNAME] $PROJET unlocked, $LOCK_FILE removed."
      else
        die"[$FUNCNAME] we can not unlock $PROJET, $LOCK_FILE still on disk." $RC_LOCK
      fi
    else
      die "[$FUNCNAME] we can not delete lockfile owned by another process" $RC_LOCK
    fi

  fi
}

cleanup_working_folder() {
  verbose "[$FUNCNAME] WORKING_FOLDER=$WORKING_FOLDER"
  if test -n "$WORKING_FOLDER" -a -d "$WORKING_FOLDER";
  then
    if test "$VERBOSE" -eq 1;
    then
      rm --recursive --verbose "$WORKING_FOLDER"
    else
      rm --recursive "$WORKING_FOLDER"
    fi
    if test ! -d "$WORKING_FOLDER";
    then
      verbose "[$FUNCNAME] $WORKING_FOLDER removed"
    fi
  fi
}

usage() {
  echo "
  cocktail -b url_base -d dossier [ -h ] -p projet [ -g url_garde ] [ -v ]
      -b : url du pad principal
      -d : nom du dossier
      -g : url du pad de page de garde (optionnel)
      -h : cette page d'aide
      -p : nom du projet
      -v : force le mode verbeux

    return codes:
      0 : OK
      1 : GENERIC ERROR
      2 : LOCK ERROR
      3 : CONFIG FILE IS MISSING
      4 : PANDOC FILTER IS MISSING OR NOT EXECUTABLE
      5 : ARGUMENTS ERRORS"
}

publish() {
  local src_folder="$1"
  local dst_folder="$2"
  verbose "[$FUNCNAME] SOURCE=$src_folder DESTINATION=$dst_folder"
  if test ! -d "$src_folder";
  then
    die "[$FUNCNAME] the folder '$src_folder' does not exists"
  fi

  if test ! -d "$dst_folder";
  then
    die "[$FUNCNAME] the folder '$dst_folder' does not exists"
  fi

  for ext in pdf docx html txt
  do
    local from="$src_folder/$PROJET.$ext"
    local to="$dst_folder/$PROJET.$ext"
    verbose "$from -> $to"
    cp -f "$from" "$to"
  done
}

### MAIN ###
base=$( cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
if test -r "$base/cocktail.conf";
then
  source "$base/cocktail.conf"
else
  die "cocktail.conf is missing, see config.conf.smp for example" $RC_CONFIG_MISSED
fi

OPTERR=1
while getopts "b:d:g:p:hv" option;
do
  case $option in
    b)
        URL_BASE=$OPTARG
        verbose "getopts: -$option) URL_BASE=$URL_BASE"
        ;;
    d)
        DOSSIER=$OPTARG
        verbose "getopts: -$option) DOSSIER=$DOSSIER"
        ;;
    g)
        URL_GARDE=$OPTARG
        verbose "getopts: -$option) URL_GARDE=$URL_GARDE"
        ;;
    h)
        usage
        exit
        ;;
    p)
        PROJET=$OPTARG
        verbose "getopts: -$option) PROJET=$PROJET"
        ;;
    v)
        # Override verbose
        VERBOSE=1
        verbose "getopts: -$option) VERBOSE=$VERBOSE"
        ;;
  esac
done

shift $(($OPTIND - 1))
verbose "ARGS=$@"

if test -z "$DOSSIER";
then
  die "getopts: -d DOSSIER is mandatory" $RC_ARGS
fi

verbose "DOSSIER=$DOSSIER"
WORKING_FOLDER="$WORKING_FOLDER/$PROJET"
verbose "WORKING_FOLDER=$WORKING_FOLDER"
mkdir -p "$WORKING_FOLDER"
cd "$WORKING_FOLDER" || die "we can't change to \"$WORKING_FOLDER\" folder"

STORE="$STORE/$DOSSIER"

verbose "STORE=$STORE"
mkdir -p "$STORE"
LOCK_FILE="$STORE/$PROJET.lock"
verbose "LOCK_FILE=$LOCK_FILE"

if test -z "$URL_BASE";
then
  die "getopts: -b URL_BASE is mandatory" $RC_ARGS
fi

init_check
lock_project
mirror_pad "$URL_BASE" "$WORKING_FOLDER/$PROJET.txt"

if test "$URL_GARDE";
then
  mirror_pad "$URL_GARDE" "$WORKING_FOLDER/garde.tex"
fi


# hack specifique Abro Tele2
touch "$WORKING_FOLDER/annexe-tableau.tex"

pad2json "$WORKING_FOLDER/$PROJET.txt" "$WORKING_FOLDER/$PROJET.json"
pad2docx "$WORKING_FOLDER/$PROJET.txt" "$WORKING_FOLDER/$PROJET.docx"
pad2html "$WORKING_FOLDER/$PROJET.txt" "$WORKING_FOLDER/$PROJET.html"
pad2markdown "$WORKING_FOLDER/$PROJET.txt" "$WORKING_FOLDER/$PROJET.markdown.txt"
pad2tex "$WORKING_FOLDER/$PROJET.txt" "$WORKING_FOLDER/$PROJET.tex"
tex2pdf "$WORKING_FOLDER/$PROJET.tex" "$WORKING_FOLDER/$PROJET.pdf"
publish "$WORKING_FOLDER" "$STORE"
unlock_project
end_with_code $RC_OK

