#!/bin/bash

if test "$TRAVIS" = "true";
then
  URL_FILE=url_test.pub.txt
else
  URL_FILE=url_test.priv.txt
fi

if test -r "$URL_FILE";
then
  URL_BASE=$(head -n1 "$URL_FILE")
  URL_GARDE=$(tail -n1 "$URL_FILE")
else
  echo "'$URL_FILE' introuvable"
  exit 1
fi

./cocktail -v \
           -d MonDossier \
           -p Abro2 \
           -b "$URL_BASE" \
           -g "$URL_GARDE"

