#!/bin/bash

echo "Test 02: 2 compilations dans le même dossier, projets différents"
echo "Les deux doivent correctement se dérouler"

# pids conserve la liste des pids
# retcode conserve le code retour de chaque pid une fois terminé
handle_child() {
  local tmp=()
  for((i=0;i<${#pids[@]};++i));
  do
    if test ! -d /proc/${pids[i]};
    then
      wait ${pids[i]}
      retcode[${pids[i]}]=$?
    else
      tmp+=(${pids[i]})
    fi
  done
  pids=(${tmp[@]})
}

set -o monitor
trap "handle_child" CHLD


# Start background processes
./cocktail -v \
           -d MonDossier \
           -p Abro2 \
           -b 'https://pad.exegetes.eu.org/p/g.DSXI1kGFT1gjor66$Abro-REP-Tele2-Principal/export/txt' \
           -g 'https://pad.exegetes.eu.org/p/g.DSXI1kGFT1gjor66$Abro-REP-Tele2-Garde/export/txt' &
pids+=($!)

./cocktail -v \
           -d MonDossier \
           -p Abro3 \
           -b 'https://pad.exegetes.eu.org/p/g.DSXI1kGFT1gjor66$Abro-REP-Tele2-Principal/export/txt' \
           -g 'https://pad.exegetes.eu.org/p/g.DSXI1kGFT1gjor66$Abro-REP-Tele2-Garde/export/txt' &
pids+=($!)

# Wait until all background processes are stopped
while [ ${#pids[@]} -gt 0 ];
do
  echo "WAITING FOR: ${pids[@]}";
  sleep 2;
done
echo STOPPED

# affichage des code retour et generation de la chaine de test
for pid in "${!retcode[@]}"
do
  statusstring="$statusstring $pid=${retcode[$pid]}"
  retcodestr="${retcodestr}${retcode[$pid]}"
done
echo $statusstring

if test $retcodestr -eq "00" -o $retcodestr -eq "00";
then
  echo "Test réussi"
  echo "Les deux processus se sont terminés en code 0"
  exit 0
else
  echo "Test échoué."
  echo "Les deux processus doivent se terminer en code 0"
  exit 1
fi

