#!/bin/bash

printf "$PRINTFPATTERN" $0 : "Lancement avec un mauvais dossier"

URL_BASE=https%3A%2F%2Fpad.exegetes.eu.org%2Fp%2Fg.DSXI1kGFT1gjor66%24Abro-REP-Tele2-Principal%2Fexport%2Ftxt
URL_GARDE=https%3A%2F%2Fpad.exegetes.eu.org%2Fp%2Fg.DSXI1kGFT1gjor66%24Abro-REP-Tele2-Garde%2Fexport%2Ftxt
DOSSIER=Un..MauvaisDosser
PROJET=Projet$$

OUTPUT=$(./cocktail -v \
           -d "$DOSSIER" \
           -p "$PROJET" \
           -b "$URL_BASE" \
           -g "$URL_GARDE" 2>&1 >/dev/null) 
RC=$?
echo -n "RC=$RC "
if test "$RC" -ne "7";
then
  # Test raté
  echo "[FAILED]"
else
  echo "[  OK  ]"
  RC=0
fi
echo "$OUTPUT"

exit "$RC"

