#!/bin/bash
MAXRC=0
testOK=0
testFAILED=0
testSKIPPED=0
testCOUNT=0

# Est utilisé dans les script appelés pour formater la sortie
export PRINTFPATTERN='%-31s %s %-70s'

# Par défaut lance tous les scripts dans t/, qui sont executables sauf lui même (altests)
# si un argument est donné il lance les scripts qui correspondent à $1* 
# exemple t/alltest 1 pour lancer tous les tests qui commencent par 1
for test in t/$1*;
do
  if test -x "$test" -a "$test" != "$0";
  then
    testCOUNT=$(($testCOUNT + 1))
    echo -n "[$testCOUNT]    "
    $test
    RC=$?
    printf "RC:=(%d) (%s)\n\n" $RC $test
    if test "$RC" -eq "99";
    then
      testSKIPPED=$(($testSKIPPED + 1))
    elif test "$RC" -ne "0";
    then
      MAXRC="$RC"
      testFAILED=$(($testFAILED + 1))
    else
      testOK=$(($testOK + 1))
    fi
  fi
done

if test "$MAXRC" -eq "0";
then
  echo "All tests : OK:$testOK/$testCOUNT FAILED:$testFAILED/$testCOUNT SKIPPED=$testSKIPPED/$testCOUNT [  OK  ]"
else
  echo "All tests : OK:$testOK/$testCOUNT FAILED:$testFAILED/$testCOUNT SKIPPED=$testSKIPPED/$testCOUNT [FAILED]"
fi

exit $MAXRC
